language: node_js
node_js:
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g nodeunit

env:
  - CXX=g++-4.8

addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - g++-4.8