language: node_js
node_js:
  - "12.2"
  - "11.10"
  - "10.15"
  - "7.7"
  - "6.9"
  - "4.2"
  - "0.12"
  - "0.11"

services:
  - xvfb

script:
  - npm build .
  - npm test

env:
  - CXX=g++-4.8

addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - g++-4.8
