language: node_js
node_js:
  - "17.4.0"
  - "16.13.2"

services:
  - xvfb

script:
  - npm build .
  - npm test

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
